#!/usr/bin/env python3
"""Add 6 missing dreams to seed-dream-content.json and re-index by date."""
import json
from pathlib import Path

project = Path(__file__).parent.parent
seed_path = project / "data" / "seed-dream-content.json"

with open(seed_path, encoding="utf-8") as f:
    dreams = json.load(f)

new_dreams = [
    {
        "dream_index": 0,
        "original_date": "2025-02-05",
        "title": "Driving the Sequoia Through Russia",
        "journal_text": "I was on a family vacation in Russia with my father Gene, my mother Jennifer, and my brother Skyler. My sister Sab was notably absent. We had brought an absurd amount of luggage \u2014 far too much \u2014 and we were staying in a Russian family\u2019s house while they were away on business. I took the lead, guiding my family through the unfamiliar town. We ate wonderful food, went skiing, and filled our days with activities. At one point, Skyler and I played Nintendo 64 back at the house, a perfect throwback to childhood.\n\nWhen it was time to leave, everything became frantic. I tried to be as thorough and clean as possible, but my parents kept leaving things behind \u2014 extra clothes, even an entire suitcase. I grew increasingly frustrated, telling them we couldn\u2019t just abandon our belongings in someone else\u2019s home. Eventually I stopped arguing and started grabbing things myself, loading everything into the car piece by piece.\n\nThen came the strangest part: I was the one driving. I didn\u2019t exactly know what I was doing behind the wheel, but it had to be me. I navigated the roads carefully, avoiding any contact with the police, steering us through unfamiliar streets. The car was our old Toyota Sequoia \u2014 the one we\u2019d sold years ago. I drove my family out of Russia in a vehicle from our past, carrying everything they\u2019d left behind.",
        "interpretation": "This dream is a remarkably clear portrait of premature responsibility and the Hero archetype activated before its time. Russia \u2014 vast, unfamiliar, governed by rules you don\u2019t fully understand \u2014 represents the foreign territory of adult responsibility that you\u2019ve been thrust into within your family system. That your sister Sab is absent is significant: the dream has selected only the core family unit in which you feel your role most acutely.\n\nThe excessive luggage is a potent symbol of psychological baggage. Your family carries more than it needs \u2014 unresolved patterns, accumulated habits, emotional weight \u2014 and much of it gets left behind carelessly. Your frantic attempts to clean and gather what your parents abandon reveals a compensatory pattern: you are the one who sees what is being neglected, who understands the social contract of borrowing someone else\u2019s space. The Russian family\u2019s absent home represents borrowed time, borrowed structures \u2014 perhaps the inherited frameworks of your parents\u2019 world that you occupy but did not build.\n\nThe Nintendo 64 moment with Skyler is a brief return to the Child archetype \u2014 pure play, uncomplicated brotherhood. It stands in sharp contrast to what follows. The shift from childhood play to desperately organizing your parents\u2019 chaos mirrors your lived experience of growing up fast.\n\nThe climactic driving scene is the dream\u2019s thesis. You are behind the wheel of the family vehicle despite not fully knowing how to drive. This is the Hero forced into action by necessity rather than readiness. The Toyota Sequoia \u2014 sold years ago \u2014 anchors this journey in the past. You are navigating your family forward using a vehicle from childhood, suggesting that the emotional patterns driving your sense of responsibility were formed long ago. Avoiding police represents navigating authority structures you don\u2019t fully trust or feel authorized by. The Shadow here is the family\u2019s collective passivity \u2014 the things left behind, the responsibility no one else claims. The question your psyche poses is profound: when does the Hero\u2019s duty become the Hero\u2019s burden?",
        "symbols": [
            {"symbol": "Toyota Sequoia", "archetype": "Child", "sentiment": "melancholic"},
            {"symbol": "Excessive Luggage", "archetype": "Shadow", "sentiment": "confrontational"},
            {"symbol": "Driving Without Knowing How", "archetype": "Hero", "sentiment": "ambivalent"},
            {"symbol": "Russia as Foreign Territory", "archetype": "Self", "sentiment": "mysterious"},
            {"symbol": "Nintendo 64", "archetype": "Child", "sentiment": "nurturing"}
        ],
        "mood": "anxious",
        "image_prompt": "A snow-covered Russian village at twilight with a dark green Toyota Sequoia SUV parked on a narrow road, its trunk open and overflowing with suitcases and scattered clothing. A solitary young man stands at the driver's door, hand on the handle, looking down the long winding road ahead that disappears into mist and birch forests. In the rearview mirror, a warm-lit wooden house glows behind them. Painted in the style of Andrew Wyeth crossed with Caspar David Friedrich, using slate grays, deep forest greens, warm amber window light, and cold blue snow.",
        "go_deeper": [
            {"exchange": 1, "user": "Why was I the one driving even though I didn't really know how?", "assistant": "The Hero archetype has been activated in you \u2014 but not through a triumphant call to adventure. It was activated by default, by the absence of someone else stepping forward. In your waking life, how often do you take the wheel in family situations not because you feel ready, but because no one else will?"},
            {"exchange": 2, "user": "Why were we driving our old Sequoia? We sold that car years ago.", "assistant": "The Sequoia is a vessel of family memory. Now you are in the driver\u2019s seat of that same vehicle. The psyche is showing you that the emotional infrastructure of your family was built in that era and has not been updated. What beliefs about your role were formed when you were young enough to ride in the backseat?"},
            {"exchange": 3, "user": "I kept trying to grab the things my parents left behind. Why did that feel so urgent?", "assistant": "What your parents leave behind becomes your responsibility. Notice the sequence: first you tried to tell them, then you gave up communicating and simply did it yourself. In your waking life, where have you stopped asking your family to carry their own weight and simply started carrying it for them?"}
        ]
    },
    {
        "dream_index": 0,
        "original_date": "2025-03-24",
        "title": "The Inheritance That Skipped Me",
        "journal_text": "There was a beautiful, expansive family-owned home in Newport Beach. My grandfather Gene was the original owner, and he had passed it down to my father, Gene, who in turn gave partial ownership to my brother Skyler. I was not included in the ownership at all.\n\nI immediately saw the potential. I suggested renting it out and even took photos of the property, studying its angles and light to create the best possible listing. But nobody wanted to do anything with it. Nobody had any sense of agency or vision. The property just sat there, full of untapped value, while my family shrugged.\n\nI felt a sharp frustration \u2014 not just about the house, but about something deeper. I wasn\u2019t part of the owners group despite being the one with the clearest vision for what to do with it. I thought my family was incapable of properly creating wealth, especially Skyler, who had been given ownership without any plan for what to do with it. Still, I kept studying the property, figuring out the ideal photos and strategy as if it were mine to manage.\n\nEventually I rode a scooter back toward home, discussing the situation with a friend along the way. The conversation was grounding. At some point, memories of my college fraternity surfaced, and I found myself mentally back in Orange County during those earlier years \u2014 a time when Newport Beach meant something different, something social and unencumbered.",
        "interpretation": "This dream strikes at the heart of one of Jung\u2019s most essential themes: the relationship between inheritance and individuation. The Newport Beach property is not merely real estate \u2014 it is a symbol of accumulated family value, legacy, and the potential for generational wealth. The patrilineal chain of transmission \u2014 Grandpa Gene to Gene to Skyler \u2014 pointedly excludes you, and this exclusion is the dream\u2019s emotional engine.\n\nIn Jungian terms, you are witnessing the family\u2019s collective approach to the Self\u2019s resources. The property represents latent wholeness \u2014 something valuable that exists within the family system but remains undeveloped. Your grandfather embodies the Wise Old Man archetype, the original holder of family wisdom and material legacy. Your father is the intermediary generation, the one who received but did not transform. Skyler, as the recipient who lacks agency, represents the Shadow side of inheritance: receiving without earning, possessing without understanding.\n\nYour frustration is not petty jealousy \u2014 it is the Hero\u2019s legitimate anguish at seeing treasure squandered. You photograph the property, study it, strategize its potential. This is the entrepreneurial spirit as archetypal function: you are the one who sees value where others see inertia. Yet the dream places you outside the ownership structure, and this is its deepest teaching. Your individuation path may require you to build your own house rather than renovate the family\u2019s.\n\nThe scooter ride home is a descent from grandiosity to groundedness. The fraternity memories transport you to Orange County as it once was \u2014 a place of belonging, youth, and possibility before the weight of family dynamics complicated your relationship to that geography. The dream asks: can you separate your vision for wealth creation from your need for family recognition? The truest inheritance may not be property at all, but the drive and clarity that makes you the one who sees what no one else can see.",
        "symbols": [
            {"symbol": "Newport Beach Property", "archetype": "Self", "sentiment": "ambivalent"},
            {"symbol": "Grandfather Gene", "archetype": "Wise Old Man", "sentiment": "protective"},
            {"symbol": "Skyler Receiving Ownership", "archetype": "Shadow", "sentiment": "confrontational"},
            {"symbol": "Scooter Ride Home", "archetype": "Hero", "sentiment": "liberating"},
            {"symbol": "Fraternity Memories", "archetype": "Child", "sentiment": "melancholic"}
        ],
        "mood": "melancholic",
        "image_prompt": "A grand Mediterranean-style home in Newport Beach bathed in late afternoon golden light, viewed from across the street through a wrought-iron gate. The house is pristine but empty. In the foreground, a lone figure on a vintage scooter rides away down a palm-tree-lined boulevard toward a distant sunset over the Pacific Ocean, casting a long shadow behind him. Rendered in the style of David Hockney's Southern California paintings with warm California gold, terracotta, ocean blue, and deep shadow purple.",
        "go_deeper": [
            {"exchange": 1, "user": "Why was I excluded from ownership when I was clearly the one with the vision?", "assistant": "You received something your family may not even recognize as an inheritance \u2014 the ability to see potential, to strategize, to create value from vision. The dream excludes you from ownership precisely to show you that your power doesn\u2019t come from what you\u2019re given. It comes from what you see."},
            {"exchange": 2, "user": "Why did I feel so frustrated with Skyler specifically?", "assistant": "Skyler carries your Shadow here \u2014 the one who receives without acting. He is the mirror image of your central wound: you act without receiving, he receives without acting. Is there a part of you that wishes you could simply receive without the compulsive need to optimize and prove?"},
            {"exchange": 3, "user": "What's the significance of the fraternity memories?", "assistant": "In college, Orange County was yours \u2014 your experience, your friendships, your coming-of-age. The family property drama reassigns that geography to the patrilineal chain. In your fraternity days, belonging was earned through presence. In the family inheritance, belonging is assigned by bloodline. Which model feels more true to who you are?"}
        ]
    },
    {
        "dream_index": 0,
        "original_date": "2025-11-04",
        "title": "The Uber Driver Was My Father",
        "journal_text": "I was with Virginia, a team leader from my Google TV job, and we were working remotely together from a place that felt familiar \u2014 somewhere in the US I recognized but couldn\u2019t quite name. We had fallen into a comfortable rhythm, and I found myself opening up to her about my life outside of work. I told her about college, how I thrived on networking, how deeply involved I was with my fraternity and all its activities. As the words left my mouth, I sensed a shift in her expression \u2014 something slightly guarded, maybe judgment, maybe just surprise. I worried I had revealed too much of myself, that the fraternity talk had triggered a negative impression. But despite that flicker of tension, there was still a genuine warmth between us, a camaraderie that held steady underneath the surface awkwardness. Then I realized I had somewhere else to be and I was running late. I scrambled to get ready, feeling the familiar anxiety of being behind schedule. Virginia was patient with me though, unhurried, almost maternal in her calm. When I finally stepped outside, my Uber had arrived \u2014 and sitting behind the wheel was my Dad. He didn\u2019t say much about it. It just was what it was. He drove me to my next destination as if this were the most natural thing in the world.",
        "interpretation": "This dream stages a powerful dialogue between your Persona \u2014 the professional mask you wear in the workplace \u2014 and the deeper, more authentic layers of your identity that lie beneath it. Virginia, as your team leader, represents the authority structure of your corporate life, the external world that evaluates and judges your competence. Your decision to share personal stories about fraternity life and networking is an act of vulnerability, a momentary lowering of the Persona to reveal the social, relational self underneath. The anxiety you feel about her reaction reflects a core tension in individuation: the fear that your authentic self will be found lacking by the figures who hold power over your professional identity.\n\nThe fraternity represents a liminal space \u2014 it belongs neither fully to childhood nor to adulthood, but to that threshold period where identity is forged through belonging, ritual, and brotherhood. Sharing this with Virginia is an attempt to integrate your past self with your present professional role, yet the Persona resists, sensing danger in such exposure.\n\nThe intimacy and camaraderie that persists despite the tension points to the Anima \u2014 the feminine principle within you that seeks genuine connection beyond roles and hierarchies. Virginia carries this projection: she is both authority figure and confidante, judge and ally. Her patience as you prepare to leave suggests a nurturing quality, an inner feminine wisdom that accepts your imperfections.\n\nThe most striking symbol is your father arriving as the Uber driver. The father archetype here operates as both the Wise Old Man and the personal father complex. He appears at the moment of transition \u2014 you are leaving one space and heading to another, symbolizing a psychic movement between identities. That your father is the vehicle for this transition suggests that your relationship with him, and with paternal authority generally, is the underlying force carrying you from one stage of life to the next. He doesn\u2019t explain himself; he simply drives. This is the unconscious operating quietly beneath conscious life, ferrying you forward whether you recognize it or not.",
        "symbols": [
            {"symbol": "Virginia the team leader", "archetype": "Anima", "sentiment": "ambivalent"},
            {"symbol": "Fraternity stories", "archetype": "Persona", "sentiment": "confrontational"},
            {"symbol": "Running late", "archetype": "Shadow", "sentiment": "threatening"},
            {"symbol": "Father as Uber driver", "archetype": "Wise Old Man", "sentiment": "mysterious"}
        ],
        "mood": "anxious",
        "image_prompt": "A dreamlike scene of a man stepping out of a warm, softly-lit home office into a misty evening street where a dark sedan waits with its headlights glowing. Behind the wheel sits an older man whose face is partially obscured by shadow. The house interior glows amber through the windows while the outside world is cool blue-violet. Painted in a modern impressionist style with visible brushstrokes, atmospheric fog blurring the boundary between indoors and outdoors.",
        "go_deeper": [
            {"exchange": 1, "user": "Why do you think I felt nervous about telling Virginia about my fraternity life?", "assistant": "Consider what the fraternity represents to you \u2014 not just the activities, but the version of yourself that existed there. When you shared that with Virginia, you were offering a self that predates your professional identity. What part of that younger self do you fear doesn\u2019t belong in your current life?"},
            {"exchange": 2, "user": "What does it mean that my dad showed up as the Uber driver?", "assistant": "Your father appears at the exact moment of transition. You didn\u2019t call for your father; you called for a stranger to drive you. Yet he appeared anyway. In the transitions happening in your waking life, where do you feel your father\u2019s influence operating silently beneath the surface?"},
            {"exchange": 3, "user": "Why was Virginia patient with me when I was running late?", "assistant": "Patience from an authority figure in a dream often signals something the psyche desperately wants but fears it cannot have \u2014 unconditional acceptance within a structure of evaluation. You were surprised by her patience. What does it say about your inner landscape that you expect judgment rather than grace from authority figures?"}
        ]
    },
    {
        "dream_index": 0,
        "original_date": "2025-12-03",
        "title": "Sunset Victory on the Pacific Coast",
        "journal_text": "It had been an incredibly stressful period \u2014 the kind where every day bleeds into the next and your mind never fully quiets. But now Cody and I were in a sports car, tearing along a highway that hugged the Pacific coast. The ocean stretched out endlessly to our left, and the road curved ahead of us like a promise. We had poured everything into a project \u2014 every ounce of mental energy, significant money, sleepless nights \u2014 and against all odds, we had barely pulled it off. As the sun began to set, painting the sky in deep oranges and pinks, I turned to Cody and said, \u2018We did it.\u2019 We knuckled up and watched the sun melt into the ocean. Someone passed a joint and I brought it to my lips, but I didn\u2019t actually inhale. Then we were on the beach, shoes off, sand cool beneath us. Our phones kept buzzing \u2014 our parents calling to check in on us. We tried to stay in the moment. Then my dad told me that Jordan Montgomery, the former Yankees pitcher, had died. It hit me with a strange, hollow surprise. The news sat in my chest like a stone, even as the waves kept rolling in.",
        "interpretation": "This dream is a profound meditation on the Hero\u2019s journey \u2014 specifically the moment of return, when the ordeal is survived and the hero must integrate the experience. The sports car on the Pacific Coast Highway is a classic symbol of the achieved life: speed, beauty, freedom, the open road. You and Cody have completed a trial that demanded everything, and the narrow margin of your success echoes the mythological motif of the hero who barely escapes the underworld.\n\nYet the dream immediately introduces dissonance. You bring the joint to your lips but do not inhale. This is a critical symbol \u2014 you are performing relaxation without fully inhabiting it. The Persona goes through the motions of celebration while something deeper refuses to let go. This suggests a Shadow element: a part of you that does not believe it deserves rest, or that fears what comes after victory.\n\nThe parents calling represent the pull of the Great Mother and Father archetypes \u2014 the original authority structures that shaped you. Their calls during your moment of hard-won independence reveal an inner tension between autonomy and the child self that still seeks approval.\n\nThen comes the death of Jordan Montgomery. In Jungian terms, the death of a sports hero is the intrusion of mortality into the victory celebration. Montgomery represents the part of achievement that is impermanent, the reminder that all victories are temporary. That this news comes from your father deepens its significance \u2014 the paternal voice delivering the message of mortality, the oldest lesson a father teaches a son. The dream asks you to hold both truths simultaneously: you did it, and nothing lasts forever.",
        "symbols": [
            {"symbol": "Sports car on Pacific Coast Highway", "archetype": "Hero", "sentiment": "liberating"},
            {"symbol": "Joint held but not inhaled", "archetype": "Shadow", "sentiment": "ambivalent"},
            {"symbol": "Parents calling", "archetype": "Great Mother", "sentiment": "nurturing"},
            {"symbol": "Death of Jordan Montgomery", "archetype": "Shadow", "sentiment": "melancholic"},
            {"symbol": "Sunset over the ocean", "archetype": "Self", "sentiment": "transformative"}
        ],
        "mood": "melancholic",
        "image_prompt": "A sleek sports car parked at the edge of a Pacific coast cliff highway at golden hour, two silhouetted figures sitting on the hood facing a massive sunset that bleeds crimson and amber across the ocean. Below, gentle waves lap a sandy beach scattered with long shadows. Cinematic widescreen composition in the style of a vintage 1970s film still, rich saturated colors with slight grain, evoking nostalgia and bittersweet triumph.",
        "go_deeper": [
            {"exchange": 1, "user": "Why did I hold the joint to my lips without actually smoking it?", "assistant": "You performed the gesture of letting go without actually letting go. Is there a part of you that believes relaxation must be earned beyond what you\u2019ve already earned? What would it mean to fully exhale after a hard-won success?"},
            {"exchange": 2, "user": "Why did my parents keep calling during this moment?", "assistant": "Your parents call at the exact moment you\u2019re trying to inhabit your adult achievement. The calls represent the internalized parental voice that still monitors you. Can you hold your parents\u2019 love without letting it reduce you back to the person you were before this victory?"},
            {"exchange": 3, "user": "What does Jordan Montgomery's death mean in this dream?", "assistant": "His death arriving mid-celebration is the psyche introducing a deeper truth: every triumph contains the seed of its own passing. Your father delivering this news is the father\u2019s ancient role \u2014 to initiate the son into the reality of impermanence."}
        ]
    },
    {
        "dream_index": 0,
        "original_date": "2025-12-15",
        "title": "The Arena of Wild Beasts",
        "journal_text": "My friend Matt Somogyi had gotten us an incredible gig \u2014 we were hired to film at a facility that hosted the most insane sport I\u2019d ever seen. The concept was brutal in its simplicity: you\u2019re placed in a room with a wild beast and you have to survive for sixty seconds. If the animal gets too close, the employees intervene and shoot it dead. Matt and I filmed the different stages and setups. Then they offered to let us try it ourselves. My friend Chris went first. He was extraordinary \u2014 he actually killed several of the animals with raw warrior instinct. The facility staff dressed him up in their gear and filmed him for promotional material. Then Cody went. He lasted about thirty seconds before the beast overwhelmed him. I heard twelve gunshots ring out as the employees took down the animal. Then it was my turn. My heart was pounding, but when I entered the arena, something calm took over. I didn\u2019t fight. I climbed \u2014 straight up, as high as I could go, putting vertical distance between me and the beast below. Then they released more beasts. I watched them from above, reading their patterns, and when the moment was right I leaped down, threading between them with a precision that surprised even me. I grabbed a rope and swung myself onto a platform surrounded by water just as the timer expired. I had survived without throwing a single punch, without any animal being harmed. Chris and I were both victors, but the cameras swarmed him for his sword skills. I stood to the side, quietly triumphant. And honestly? I felt great.",
        "interpretation": "This dream is a masterful staging of the Hero archetype explored through three distinct strategies of confrontation, each embodied by a different friend who represents a facet of your own psyche. The arena with wild beasts is the archetypal space of initiation \u2014 the place where the ego must face the untamed, instinctual forces of the unconscious.\n\nChris represents the classical Hero \u2014 the warrior who meets the Shadow head-on with force and skill. He kills the beasts and is rewarded with immediate recognition and social glory.\n\nCody represents the unprepared ego \u2014 the part of the self that enters the confrontation without sufficient strategy and is overwhelmed. The twelve gunshots are a visceral reminder of what happens when the Shadow overtakes us.\n\nThen there is your approach, and it is the most Jungian of the three. You climb above the conflict. You observe. You read patterns. You move with grace rather than aggression. The rope swing to the water platform is deeply symbolic: water represents the unconscious, and you land safely upon it rather than drowning in it.\n\nThat you feel great despite receiving no public recognition reveals a crucial stage of individuation: the shift from external validation to internal knowing. The Persona craves the camera and the crowd; the Self knows what it has accomplished. This is the Trickster\u2019s wisdom \u2014 winning without fighting, surviving through cleverness rather than force. The dream affirms that your way of meeting life\u2019s challenges, though quieter and less celebrated, is no less heroic.",
        "symbols": [
            {"symbol": "Wild beasts in the arena", "archetype": "Shadow", "sentiment": "threatening"},
            {"symbol": "Chris the warrior victor", "archetype": "Hero", "sentiment": "confrontational"},
            {"symbol": "Climbing above the beasts", "archetype": "Trickster", "sentiment": "liberating"},
            {"symbol": "Rope swing to water platform", "archetype": "Self", "sentiment": "transformative"},
            {"symbol": "Twelve gunshots", "archetype": "Shadow", "sentiment": "threatening"}
        ],
        "mood": "chaotic",
        "image_prompt": "A vast indoor arena with towering industrial scaffolding and platforms at multiple levels. A lone figure perches high on a metal beam above the arena floor, poised and calm, while shadowy beast-like forms prowl below in dusty golden spotlight beams. A rope hangs from the ceiling near a wooden platform surrounded by dark reflective water. Rendered in dark Renaissance chiaroscuro style with deep blacks, warm amber spotlights, and cool blue shadows, conveying both danger and quiet mastery.",
        "go_deeper": [
            {"exchange": 1, "user": "Why did I choose to climb instead of fight?", "assistant": "Your instinct to climb reveals how your psyche processes threat. You sought perspective \u2014 literally rising above the situation. In your waking life, do you tend to seek elevation through analysis or strategic patience rather than direct confrontation? The deeper question is whether you fully trust this approach, or whether some part of you still envies Chris\u2019s sword."},
            {"exchange": 2, "user": "What does it mean that Chris got all the attention even though we both survived?", "assistant": "Chris\u2019s strategy is visible, dramatic, and immediately legible to an audience. Yours is internal and subtle. But notice what the dream gives you: not attention, but peace. You felt great. That feeling is the Self speaking, telling you that your worth is not determined by who is watching."},
            {"exchange": 3, "user": "What do the different outcomes for me, Chris, and Cody represent?", "assistant": "Each friend embodies a strategy that lives within you. Chris is your inner warrior. Cody represents the part that sometimes rushes in before it\u2019s ready. And you are the integrated self that has learned from both. The dream also asks: are there moments where Chris\u2019s directness would serve you better?"}
        ]
    },
    {
        "dream_index": 0,
        "original_date": "2026-03-03",
        "title": "Red Dress in the Arctic Map",
        "journal_text": "I was in San Francisco, surrounded by good friends and the familiar warmth of the city. I sat down to dinner with Ashley and Mitch, and as the conversation flowed, it turned to Malek \u2014 a girl I\u2019ve been thinking about. I had just texted her for the first time in a while. Then something strange happened: we started seeing her everywhere, appearing around us in a striking red dress, looking absolutely stunning. Ashley studied her closely, as if examining something important on my behalf.\n\nSuddenly the scene shifted. I was with Malek somewhere in Europe, sitting at a restaurant with a relaxed guy who spoke French. They were teaching me French through playful puzzle games, and we hopped between multiple restaurants in a single night, sampling all kinds of French cuisine. It felt effortless and alive. After they left, I walked past a vending machine stocked with every drink we\u2019d been enjoying \u2014 all the same varieties, lined up neatly.\n\nThen I was back in my apartment, and my brother Skyler was there. I found myself staring at a map of the Arctic, and enormous fish were swimming through it \u2014 not illustrations, but living creatures moving within the map itself. I realized the map was revealing hidden information, buried secrets. I noticed a secret island that wasn\u2019t fully visible, partially concealed at the edge. I felt a surge of discovery. I offered to order food for Skyler and me, and he liked that idea. We settled in together.",
        "interpretation": "This dream unfolds in three acts, each representing a distinct movement in your individuation process. The San Francisco dinner scene establishes your social Persona. When conversation turns to Malek, the Anima begins to emerge. Her repeated appearances in a red dress are profoundly symbolic: red is the color of passion, vitality, and the life force itself. Malek is carrying your Anima projection \u2014 she embodies the feminine qualities your psyche is reaching toward. That Ashley examines her closely suggests your inner circle is helping you evaluate this projection.\n\nThe European restaurant scene represents a threshold crossing. You are being initiated into a new language \u2014 French, the language of your imminent move to Paris. The puzzle games indicate that this learning is not merely intellectual but ludic and soulful. The vending machine afterward symbolizes the collective unconscious offering standardized versions of what you just experienced authentically \u2014 a warning against settling for the mass-produced version of life.\n\nThe final act is the most numinous. The Arctic map with living fish is a powerful image of the Self. Maps represent conscious orientation, but this map contains living creatures, meaning your unconscious is alive within your framework of understanding. The enormous fish are ancient symbols of content rising from psychic depths. The secret island represents undiscovered aspects of your Self \u2014 potential not yet fully visible but sensed. That you share this moment with Skyler and offer to nourish him suggests the brotherly bond carries a nurturing dimension. The dream\u2019s trajectory \u2014 from social self, through romantic and cultural initiation, to cosmic discovery \u2014 maps a complete individuation sequence.",
        "symbols": [
            {"symbol": "Red Dress", "archetype": "Anima", "sentiment": "mysterious"},
            {"symbol": "French Puzzle Games", "archetype": "Trickster", "sentiment": "liberating"},
            {"symbol": "Arctic Map with Living Fish", "archetype": "Self", "sentiment": "transformative"},
            {"symbol": "Secret Island", "archetype": "Self", "sentiment": "mysterious"},
            {"symbol": "Vending Machine", "archetype": "Persona", "sentiment": "ambivalent"}
        ],
        "mood": "mysterious",
        "image_prompt": "A dreamy surrealist scene split into three layers: a San Francisco cityscape at golden hour in the background, a cozy European restaurant with warm candlelight in the middle ground, and in the foreground a luminous Arctic map spread on a wooden table with enormous translucent fish swimming through its ocean regions and a partially hidden island glowing at the edge. A figure in a vivid red dress appears ethereally in the distance. Painted blending Edward Hopper with Remedios Varo, using deep teals, warm ambers, and striking crimson accents.",
        "go_deeper": [
            {"exchange": 1, "user": "Why do I keep seeing Malek everywhere in the dream, and why was she always in red?", "assistant": "Red is the color of eros, desire, and the raw life force. What qualities does Malek embody that you most admire? Are those qualities you have cultivated in yourself, or aspects you\u2019ve projected outward? The Anima often appears as an idealized romantic figure precisely because she carries parts of your own soul you haven\u2019t yet claimed."},
            {"exchange": 2, "user": "What does it mean that the map of the Arctic had living fish swimming in it?", "assistant": "A map is your conscious understanding of the world. But this map is alive. The fish suggest that your unconscious is no longer separate from your conscious orientation \u2014 it is breaking through. The hidden island represents something in your psyche that exists but is not yet fully visible. What area of your life holds untapped potential you can almost see but not quite grasp?"},
            {"exchange": 3, "user": "Is it meaningful that I offered to order food for Skyler at the end?", "assistant": "Throughout this dream you move from receiving to giving. This arc mirrors individuation: we must first be nourished by the unconscious before we can nourish others. Your own journey of discovery is not separate from your role in your family."}
        ]
    }
]

dreams.extend(new_dreams)
dreams.sort(key=lambda d: d["original_date"])

for i, d in enumerate(dreams, 1):
    d["dream_index"] = i

with open(seed_path, "w", encoding="utf-8") as f:
    json.dump(dreams, f, indent=2, ensure_ascii=False)

print(f"Total dreams: {len(dreams)}")
print(f"Symbols: {sum(len(d['symbols']) for d in dreams)}")
print(f"Go-deeper exchanges: {sum(len(d['go_deeper']) for d in dreams)}")
